"""
Multi-step objective generation pipeline.

All weights, targets, categories, and appraisal_logic are generated by the model
across three targeted prompts. Python only injects rules into prompts and orchestrates calls.

  Step 1 (LLM) — draft SMART text + BSC/LOS mapping
  Step 2 (LLM) — assign weights, measures, targets, categories (+ critical target)
  Step 3 (LLM) — write appraisal_logic for every objective
"""
from __future__ import annotations

import hashlib
import json
import sys
from datetime import datetime
from typing import Any
from collections.abc import Callable

from config import (
    OLLAMA_MODEL,
    LLM_BACKEND,
    STEP3_OLLAMA_TIMEOUT_SECONDS,
    STEP3_VLLM_TIMEOUT_SECONDS,
)
from cache.generation_cache import (
    context_fingerprint,
    get_cached_step1_drafts,
    set_cached_step1_drafts,
    step1_cache_key,
)

from .config.grade_bands import CRITICAL_TARGET_ROLE_LABEL, EmployeeProfile, parse_employee_query
from .llm_client import LLMUnavailableError, chat_json, check_llm_available
from .json_utils import build_repair_prompt, parse_llm_json
from .prompts import build_step1_prompt, build_step2_prompt, build_step3_prompt, build_all_prompts
from .prompts.loader import step1_json_example, step2_json_example, step3_json_example
from .validator import (
    normalize_objectives,
    sum_weights,
    validate_objectives,
    validate_step1_objectives,
)


DEFAULT_MODEL = OLLAMA_MODEL
MAX_JSON_RETRIES = 2
MAX_STEP_RETRIES = 2
APPRAISAL_FIELDS = ("rating_5", "rating_4", "rating_3", "rating_2", "rating_1")

# Bump when prompt templates or fragments change — invalidates prior seeds for audits.
PROMPT_VERSION = "1.1.0"
STEP1_TEMPERATURE_DEFAULT = 0.3
STRUCTURED_STEP_TEMPERATURE = 0.0
ProgressCallback = Callable[[dict[str, Any]], None]


def _step_log(message: str) -> None:
    print(message)
    sys.stdout.flush()


def _employee_key(profile: EmployeeProfile) -> str:
    """Stable composite key when no explicit employee_id is supplied."""
    return "|".join([
        profile.division.strip().lower(),
        profile.department.strip().lower(),
        profile.unit.strip().lower(),
        profile.job_title.strip().lower(),
        str(profile.job_grade),
    ])


def compute_generation_seed(
    employee_id: str,
    fiscal_year: int | str,
    prompt_version: str = PROMPT_VERSION,
) -> int:
    """Derive a deterministic Ollama seed for reproducible generation."""
    key = f"{employee_id}|{fiscal_year}|{prompt_version}"
    digest = hashlib.sha256(key.encode()).digest()
    return int.from_bytes(digest[:8], "big") % (2**63 - 1)


def _resolve_generation_context(
    context: dict,
    profile: EmployeeProfile,
) -> tuple[str, int, int]:
    employee_id = str(context.get("employee_id") or _employee_key(profile)).strip()
    fiscal_year_raw = context.get("fiscal_year")
    fiscal_year = int(fiscal_year_raw) if fiscal_year_raw is not None else datetime.now().year
    seed = compute_generation_seed(employee_id, fiscal_year, PROMPT_VERSION)
    return employee_id, fiscal_year, seed


# Fields Step 3 must not alter (everything except appraisal_logic).
STEP2_PRESERVED_FIELDS = (
    "objective", "measure", "target", "weight_percent", "category",
    "tracking_source", "time_frame", "bsc_kpi", "bsc_strategic_objective",
    "los_alignment", "source", "draft_id",
)


def _call_llm(
    system: str,
    user: str,
    *,
    model: str,
    temperature: float,
    num_predict: int,
    seed: int | None = None,
    schema_example: str | None = None,
    label: str = "llm",
    timeout_seconds: float | None = None,
) -> dict:
    last_error: json.JSONDecodeError | None = None
    raw_response = ""

    for attempt in range(MAX_JSON_RETRIES + 1):
        attempt_label = label if attempt == 0 else f"{label}_retry{attempt}"
        raw_response = chat_json(
            system, user,
            model=model, temperature=temperature, num_predict=num_predict, seed=seed,
            label=attempt_label,
            timeout_seconds=timeout_seconds,
        )
        try:
            return parse_llm_json(raw_response)
        except json.JSONDecodeError as exc:
            last_error = exc
            if attempt < MAX_JSON_RETRIES:
                continue

    if schema_example and raw_response:
        repair_sys, repair_user = build_repair_prompt(raw_response, schema_example)
        repair_raw = chat_json(
            repair_sys, repair_user,
            model=model,
            temperature=STRUCTURED_STEP_TEMPERATURE,
            num_predict=num_predict,
            seed=seed,
            label=f"{label}_repair",
            timeout_seconds=timeout_seconds,
        )
        try:
            return parse_llm_json(repair_raw)
        except json.JSONDecodeError as exc:
            last_error = exc

    assert last_error is not None
    raise last_error


def _norm_str(val) -> str:
    if val is None:
        return ""
    return str(val).strip()


def _weights_match(a, b) -> bool:
    try:
        fa = float(a) if a is not None else 0.0
        fb = float(b) if b is not None else 0.0
        return abs(fa - fb) <= 0.01
    except (TypeError, ValueError):
        return _norm_str(a) == _norm_str(b)


def _verify_step2_preservation(
    step2_objectives: list[dict],
    step3_objectives: list[dict],
) -> list[str]:
    """Return human-readable mismatch messages; empty list means Step 3 preserved Step 2."""
    mismatches: list[str] = []

    if len(step2_objectives) != len(step3_objectives):
        mismatches.append(
            f"Objective count changed: Step 2 had {len(step2_objectives)}, "
            f"Step 3 returned {len(step3_objectives)}."
        )
        return mismatches

    for i, (s2, s3) in enumerate(zip(step2_objectives, step3_objectives)):
        for field in STEP2_PRESERVED_FIELDS:
            v2, v3 = s2.get(field), s3.get(field)
            if field == "weight_percent":
                if not _weights_match(v2, v3):
                    mismatches.append(
                        f"Objective {i + 1}: weight_percent changed from {v2!r} to {v3!r}."
                    )
            elif _norm_str(v2) != _norm_str(v3):
                mismatches.append(
                    f"Objective {i + 1}: {field} changed from {v2!r} to {v3!r}."
                )

    return mismatches


def _verify_appraisal_complete(objectives: list[dict]) -> list[str]:
    """Return errors when Step 3 objectives lack full appraisal_logic."""
    errors: list[str] = []
    for i, obj in enumerate(objectives):
        appraisal = obj.get("appraisal_logic")
        if not isinstance(appraisal, dict):
            errors.append(f"Objective {i + 1}: missing appraisal_logic.")
            continue
        for field in APPRAISAL_FIELDS:
            if not str(appraisal.get(field, "")).strip():
                errors.append(f"Objective {i + 1}: missing appraisal_logic.{field}.")
    return errors


def _merge_step3_appraisal(step2_objectives: list[dict], step3_objectives: list[dict]) -> list[dict]:
    """Preserve Step 2 fields while adopting appraisal output from Step 3."""
    merged: list[dict] = []
    for s2, s3 in zip(step2_objectives, step3_objectives):
        row = dict(s2)
        if isinstance(s3, dict) and isinstance(s3.get("appraisal_logic"), dict):
            row["appraisal_logic"] = dict(s3["appraisal_logic"])
        merged.append(row)
    return merged


def _run_step3(
    profile: EmployeeProfile,
    objectives: list[dict],
    *,
    model: str,
    temperature: float,
    num_predict: int,
    seed: int | None = None,
) -> list[dict]:
    schema = step3_json_example(
        profile.critical_weight,
        profile.remaining_weight,
        CRITICAL_TARGET_ROLE_LABEL.get(profile.grade_band, "Manager's"),
    )
    sys3, user3 = build_step3_prompt(profile, objectives)
    _step_log("  Step 3/3: calling LLM (appraisal logic) ...")

    last_errors: list[str] = []
    step3_timeout_seconds = (
        STEP3_VLLM_TIMEOUT_SECONDS if LLM_BACKEND == "vllm" else STEP3_OLLAMA_TIMEOUT_SECONDS
    )

    for attempt in range(MAX_STEP_RETRIES + 1):
        step3 = _call_llm(
            sys3, user3,
            model=model, temperature=temperature, num_predict=num_predict,
            seed=seed,
            schema_example=schema,
            label="step3_appraisal",
            timeout_seconds=step3_timeout_seconds,
        )
        final_objectives = step3.get("objectives")
        if not final_objectives:
            continue

        merged_objectives = _merge_step3_appraisal(objectives, final_objectives)
        preservation_mismatches = _verify_step2_preservation(objectives, final_objectives)
        appraisal_gaps = _verify_appraisal_complete(merged_objectives)
        if not appraisal_gaps:
            if preservation_mismatches:
                _step_log(
                    "  Step 3 note: model changed Step 2 fields; preserved Step 2 and applied appraisal only."
                )
            return merged_objectives
        last_errors = preservation_mismatches + appraisal_gaps

    if last_errors:
        raise ValueError(
            "Step 3 incomplete: " + "; ".join(last_errors[:5])
        )
    raise ValueError("Step 3 returned no objectives")


def generate_objectives(
    context: dict,
    num_objectives: int,
    *,
    model: str = DEFAULT_MODEL,
    temperature: float = STEP1_TEMPERATURE_DEFAULT,
    progress_callback: ProgressCallback | None = None,
) -> dict[str, Any]:
    profile = parse_employee_query(context.get("query", ""))
    num_drafts = max(1, num_objectives - 1)
    employee_id, fiscal_year, seed = _resolve_generation_context(context, profile)

    check_llm_available(model)

    # Step 1 — draft objectives (cache hit skips LLM when profile/context unchanged)
    sys1, user1 = build_step1_prompt(profile, context, num_drafts)
    ctx_fp = context_fingerprint(
        context.get("jd_context", ""),
        context.get("bsc_context", ""),
        context.get("los_context", ""),
    )
    s1_key = step1_cache_key(
        employee_id=employee_id,
        fiscal_year=fiscal_year,
        prompt_version=PROMPT_VERSION,
        num_drafts=num_drafts,
        context_fingerprint=ctx_fp,
    )
    drafts: list = []
    step1_cache_hit = False
    cached_drafts = get_cached_step1_drafts(s1_key)
    if cached_drafts and len(cached_drafts) >= num_drafts:
        drafts = cached_drafts[:num_drafts]
        step1_cache_hit = True
        _step_log("  Step 1/3: cache hit — skipping draft LLM call")
    else:
        _step_log("  Step 1/3: calling LLM (draft objectives) — this may take a few minutes ...")
        for attempt in range(MAX_STEP_RETRIES + 1):
            step1 = _call_llm(
                sys1, user1,
                model=model, temperature=temperature, seed=seed,
                num_predict=max(2048, num_drafts * 350),
                schema_example=step1_json_example(num_drafts),
                label="step1_draft",
            )
            drafts = step1.get("drafts", [])
            if len(drafts) >= num_drafts:
                break
        if len(drafts) < num_drafts:
            raise ValueError(
                f"Step 1 returned {len(drafts)} drafts, expected at least {num_drafts}."
            )
        set_cached_step1_drafts(s1_key, drafts)

    # Validate Step 1 output against step1_rules.txt (non-fatal — logged and
    # surfaced to callers, never blocks Step 2 from running).
    # If you separately have the exact BSC KPI label list (not just the
    # formatted bsc_context text), pass it as context["bsc_kpis"] to also
    # verify each draft's bsc_kpi is copied verbatim from that list.
    # step1_warnings = validate_step1_objectives(drafts, bsc_kpis=context.get("bsc_kpis"))
    # if step1_warnings:
    #     _step_log(f"  Step 1 warnings: {step1_warnings}")

    if progress_callback:
        preview_objectives: list[dict[str, Any]] = []
        for d in drafts:
            preview_objectives.append(
                {
                    "objective": d.get("objective", ""),
                    "measure": "Pending Step 2",
                    "target": "Pending Step 2",
                    "weight_percent": 0,
                    "category": "Cannot Exceed",
                    "tracking_source": "System",
                    "time_frame": "Annual",
                    "source": "LLM Draft",
                    "bsc_kpi": d.get("bsc_kpi"),
                    "bsc_strategic_objective": d.get("bsc_strategic_objective"),
                    "los_alignment": d.get("los_alignment"),
                    "appraisal_logic": None,
                }
            )
        progress_callback(
            {
                "stage": "step1_draft",
                "message": "Draft objectives generated. Step 2 is in progress.",
                # "step1_warnings": step1_warnings,
                "partial_result": {
                    "employee_profile": {
                        "division": profile.division,
                        "department": profile.department,
                        "unit": profile.unit,
                        "job_title": profile.job_title,
                        "job_grade": profile.job_grade,
                        "grade_band": profile.grade_band,
                    },
                    "objectives": preview_objectives,
                    "total_weight": 0,
                    "pipeline_meta": {"stage": "step1_draft"},
                },
            }
        )

    # Step 2 — metrics (retry if objective count wrong)
    sys2, user2 = build_step2_prompt(profile, drafts)
    objectives: list = []
    _step_log("  Step 2/3: calling LLM (metrics & weights) ...")
    for attempt in range(MAX_STEP_RETRIES + 1):
        step2 = _call_llm(
            sys2, user2,
            model=model, temperature=STRUCTURED_STEP_TEMPERATURE, seed=seed,
            num_predict=max(3072, num_objectives * 450),
            schema_example=step2_json_example(
                profile.critical_weight,
                profile.remaining_weight,
                CRITICAL_TARGET_ROLE_LABEL.get(profile.grade_band, "Manager's"),
            ),
            label="step2_metrics",
        )
        objectives = step2.get("objectives", [])
        if len(objectives) == num_objectives:
            break
    if len(objectives) != num_objectives:
        raise ValueError(
            f"Step 2 returned {len(objectives)} objectives, expected {num_objectives}."
        )
    if progress_callback:
        progress_callback(
            {
                "stage": "step2_metrics",
                "message": "Objectives with measures/targets/weights ready. Step 3 is in progress.",
                "partial_result": {
                    "employee_profile": {
                        "division": profile.division,
                        "department": profile.department,
                        "unit": profile.unit,
                        "job_title": profile.job_title,
                        "job_grade": profile.job_grade,
                        "grade_band": profile.grade_band,
                    },
                    "objectives": objectives,
                    "total_weight": sum_weights(objectives),
                    "pipeline_meta": {"stage": "step2_metrics"},
                },
            }
        )

    # Step 3 — appraisal_logic (model-generated)
    if progress_callback:
        progress_callback(
            {
                "stage": "step3_appraisal",
                "message": "Objectives with weights ready. Step 3 is writing appraisal logic.",
                "partial_result": {
                    "employee_profile": {
                        "division": profile.division,
                        "department": profile.department,
                        "unit": profile.unit,
                        "job_title": profile.job_title,
                        "job_grade": profile.job_grade,
                        "grade_band": profile.grade_band,
                    },
                    "objectives": objectives,
                    "total_weight": sum_weights(objectives),
                    "pipeline_meta": {"stage": "step3_appraisal"},
                },
            }
        )

    try:
        final_objectives = _run_step3(
            profile, objectives,
            model=model, temperature=STRUCTURED_STEP_TEMPERATURE, seed=seed,
            num_predict=max(3072, num_objectives * 500),
        )
    except Exception:
        _step_log("  Step 3 failed before completion.")
        if progress_callback:
            progress_callback(
                {
                    "stage": "step3_failed",
                    "message": "Step 3 failed. Returning Step 2 objectives without appraisal.",
                    "partial_result": {
                        "employee_profile": {
                            "division": profile.division,
                            "department": profile.department,
                            "unit": profile.unit,
                            "job_title": profile.job_title,
                            "job_grade": profile.job_grade,
                            "grade_band": profile.grade_band,
                        },
                        "objectives": objectives,
                        "total_weight": sum_weights(objectives),
                        "pipeline_meta": {"stage": "step3_failed"},
                    },
                }
            )
        raise

    normalized, field_errors = normalize_objectives(final_objectives)
    if field_errors:
        raise ValueError(json.dumps({"validation_errors": field_errors}))

    total_weight = sum_weights(normalized)
    warnings = validate_objectives(normalized, profile)

    return {
        "employee_profile": {
            "division": profile.division,
            "department": profile.department,
            "unit": profile.unit,
            "job_title": profile.job_title,
            "job_grade": profile.job_grade,
            "grade_band": profile.grade_band,
        },
        "objectives": normalized,
        "total_weight": total_weight,
        "pipeline_meta": {
            "steps_run": (
                ["step2_metrics", "step3_appraisal"]
                if step1_cache_hit
                else ["step1_draft", "step2_metrics", "step3_appraisal"]
            ),
            "step1_cache_hit": step1_cache_hit,
            "num_drafts_requested": num_drafts,
            "num_drafts_received": len(drafts),
            "num_objectives_received": len(normalized),
            "prompt_version": PROMPT_VERSION,
            "employee_id": employee_id,
            "fiscal_year": fiscal_year,
            "seed": seed,
            "temperatures": {
                "step1": temperature,
                "step2": STRUCTURED_STEP_TEMPERATURE,
                "step3": STRUCTURED_STEP_TEMPERATURE,
            },
            "prompt_chars": {
                "step1": len(user1),
                "step2": len(user2),
                "step3": len(build_step3_prompt(profile, objectives)[1]),
            },
            "warnings": warnings,
            # "step1_warnings": step1_warnings,
        },
    }


def get_prompt_preview(context: dict, num_objectives: int) -> dict[str, str]:
    """Return all step prompts for debugging without calling Ollama."""
    profile = parse_employee_query(context.get("query", ""))
    prompts = build_all_prompts(profile, context, num_objectives)
    return {
        "step1_system": prompts["step1_draft"][0],
        "step1_user": prompts["step1_draft"][1],
        "step2_user": prompts["step2_metrics"][1],
        "step3_user": prompts["step3_appraisal"][1],
        "num_drafts": str(max(1, num_objectives - 1)),
        "remaining_weight": str(profile.remaining_weight),
    }